version: '2'
services:
  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  s3:
    image: minio/minio:RELEASE.2020-02-27T00-23-05Z
    command: ['server', '/data']
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: 'ACCESS'
      MINIO_SECRET_KEY: 'SuperS3cret'
    volumes:
      - s3-data:/data
  redis:
    image: redis:5.0
    ports:
      - 6379:6379
  rabbit:
    image: rabbitmq:3.8-management
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  s3-data: {}
  mongo-data: {}
