openapi: 3.0.0
info:
  title: Have I not Been Owned
  version: 0.1.0
servers:
  - url: /api/v1
paths:
  /breached_emails/{email}:
    get:
      x-openapi-router-controller: have_i_not_been_owned.api.controllers.breached_emails_controller
      operationId: get_breached_email
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
            format: email
      responses:
        200:
          description: Information about the breached email
          content:
            application/json:
              schema:
                type: object
        404:
          description: Email not present in any data breaches
          content:
            application/json:
              schema:
                type: object
  /domains/{domain}:
    get:
      x-openapi-router-controller: have_i_not_been_owned.api.controllers.breached_emails_controller
      operationId: get_breached_domain
      parameters:
        - name: domain
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Information about the breached email
          content:
            application/json:
              schema:
                type: object
        404:
          description: Email not present in any data breaches
          content:
            application/json:
              schema:
                type: object
